### ISSUE TITLE
konverzija Trendi v vert

### ISSUE THREAD

**Issue by iztokkosem** [clarinsi/TEI-conversions#1]
Tomaž, sem pogledal in edini, kar se sprašujem, je format datuma. Namreč, tu si dobil dnevno datoteko, ampak za korpus bomo uporabili mesečne datoteke, recimo Delo.si za januar 2021 (v eni datoteki bo združenih več posameznih člankov). Bi bilo potem za iskanja dobro, če tudi posamezni članki dobijo podatek o datumu, ki je omejen na mesec, npr. "2021-01"?

Tu imamo v mislih predvsem gledanje statistike zadetkov, recimo če bi poiskal "hiša", bi videl pojavitve po mesecih (trenutno od 2019 naprej), ne po dnevih.

**Comment by TomazErjavec** [comment]
Oprosti @iztokkosem, tole mi je čisto ušlo, tako tule (ker nisem imel nastavljenega spremljanja), kot tudi na Redmine. Sedaj sem nastavil, da sem obveščen o vseh zahtevkih, sicer je pa privzeto, da se obvešča samo, ko je nekdo omenjen, torej, če bo še kaj kje drugje na GitHub, dodaj @TomazErjavec v besedilo.

To, da issue ne moreš dodeliti meni, je pa normalno, dodeljuje šefe :)

In, ker smo s temle že odšli daleč naprej, kar zapiram. Ampak hvala za issue No. 1!
